[package]
name = "variable"
version = "2.3.5"
authors = ["Vlad Ion <vlad.ion@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
